name: p2d_fast_solver-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jax=0.3.0
  - scikit-umfpack=0.3.3
  - gcc=12.1.0
  - suitesparse=5.10.1
  - numpy=1.22.3
#  - nose=1.3.7
#  - jupyter=1.0.0
  - matplotlib=3.7.1
  - numba=0.57.1
#prefix: /home/ilone/miniconda3/envs/p2d_fast_solver-env
